# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pago_proximo", "Pago próximo"),
                            ("pago_vencido", "Pago vencido"),
                            ("contrato_por_vencer", "Contrato por vencer"),
                            ("general", "General"),
                        ],
                        max_length=25,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("mensaje", models.TextField(blank=True)),
                ("fecha_programada", models.DateTimeField()),
                (
                    "medio",
                    models.CharField(
                        choices=[
                            ("email", "Correo electrónico"),
                            ("sms", "SMS"),
                            ("push", "Notificación push"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intento_numero", models.PositiveSmallIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("fallido", "Fallido"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("mensaje_error", models.TextField(blank=True)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "notificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notificaciones.notificacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de notificación",
                "verbose_name_plural": "Logs de notificaciones",
                "db_table": "notificacion_logs",
                "ordering": ["intento_numero"],
            },
        ),
    ]
