# Generated by Django 4.2.7 on 2026-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="leida",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ya vio esta notificación en la app",
            ),
        ),
    ]
