# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contratos", "0001_initial"),
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Identificador del periodo, ej: 2026-03, 2026-03-15",
                        max_length=30,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_limite", models.DateField()),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transferencia", "Transferencia bancaria"),
                            ("efectivo", "Efectivo"),
                            ("deposito", "Depósito bancario"),
                            ("tarjeta", "Tarjeta"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100)),
                (
                    "comprobante_url",
                    models.FileField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                (
                    "recargo_mora",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("vencido", "Vencido"),
                            ("parcial", "Pago parcial"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pagos",
                "ordering": ["-fecha_limite"],
            },
        ),
        migrations.CreateModel(
            name="FichaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_referencia", models.CharField(max_length=50)),
                (
                    "clabe_interbancaria",
                    models.CharField(max_length=18, verbose_name="CLABE interbancaria"),
                ),
                ("banco", models.CharField(max_length=100)),
                (
                    "archivo_pdf",
                    models.FileField(blank=True, null=True, upload_to="fichas_pago/"),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha",
                        to="pagos.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de pago",
                "verbose_name_plural": "Fichas de pago",
                "db_table": "fichas_pago",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_fiscal", models.CharField(max_length=100, unique=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "xml_path",
                    models.FileField(blank=True, null=True, upload_to="facturas/xml/"),
                ),
                (
                    "pdf_path",
                    models.FileField(blank=True, null=True, upload_to="facturas/pdf/"),
                ),
                ("fecha_emision", models.DateTimeField()),
                (
                    "datos_fiscales_emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_como_emisor",
                        to="fiscal.datosfiscales",
                    ),
                ),
                (
                    "datos_fiscales_receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_como_receptor",
                        to="fiscal.datosfiscales",
                    ),
                ),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura",
                        to="pagos.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "db_table": "facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
