# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Propietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("folio_ine", models.CharField(blank=True, max_length=20)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("propietario", "Propietario"),
                        ],
                        default="propietario",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Propietario",
                "verbose_name_plural": "Propietarios",
                "db_table": "propietarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Credencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contrasena_hash", models.CharField(max_length=255)),
                (
                    "token_recuperacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.PositiveIntegerField(default=0)),
                ("bloqueado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credencial",
                        to="autenticacion.propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial",
                "verbose_name_plural": "Credenciales",
                "db_table": "credenciales",
            },
        ),
    ]
