# Generated by Django 6.0.2 on 2026-03-27 03:47

import autenticacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0002_propietario_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("folio_ine", models.CharField(blank=True, max_length=20)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="administradores/fotos/"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
                "db_table": "administradores",
                "ordering": ["-created_at"],
            },
            bases=(autenticacion.models.AuthUserMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="propietario",
            name="rol",
        ),
        migrations.CreateModel(
            name="CredencialAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contrasena_hash", models.CharField(max_length=255)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("intentos_fallidos", models.PositiveIntegerField(default=0)),
                ("bloqueado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administrador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credencial",
                        to="autenticacion.administrador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial de administrador",
                "verbose_name_plural": "Credenciales de administradores",
                "db_table": "credenciales_admin",
            },
        ),
    ]
