# Generated by Django 6.0.2 on 2026-03-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0003_administrador_remove_propietario_rol_credencialadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="propietario",
            name="banco",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="propietario",
            name="clabe_interbancaria",
            field=models.CharField(
                blank=True, max_length=18, verbose_name="CLABE interbancaria"
            ),
        ),
    ]
