# Generated by Django 6.0.2 on 2026-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("propiedad", "Propiedad"),
                            ("contrato", "Contrato"),
                            ("arrendatario", "Arrendatario"),
                            ("propietario", "Propietario"),
                            ("reporte", "Reporte de mantenimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entidad_id",
                    models.PositiveBigIntegerField(
                        help_text="PK de la entidad asociada"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("contrato_pdf", "Contrato PDF"),
                            ("ine", "INE"),
                            ("comprobante_domicilio", "Comprobante de domicilio"),
                            ("foto", "Fotografía"),
                            ("escritura", "Escritura"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("ruta_archivo", models.FileField(upload_to="documentos/")),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "documentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tipo_entidad", "entidad_id"],
                        name="documentos_tipo_en_d24625_idx",
                    )
                ],
            },
        ),
    ]
