# Generated by Django 6.0.2 on 2026-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatosFiscales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("propietario", "Propietario"),
                            ("arrendatario", "Arrendatario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entidad_id",
                    models.PositiveBigIntegerField(
                        help_text="PK del Propietario o Arrendatario según tipo_entidad"
                    ),
                ),
                ("nombre_o_razon_social", models.CharField(max_length=255)),
                ("rfc", models.CharField(max_length=13, verbose_name="RFC")),
                ("regimen_fiscal", models.CharField(max_length=100)),
                ("uso_cfdi", models.CharField(max_length=10, verbose_name="Uso CFDI")),
                ("codigo_postal", models.CharField(max_length=5)),
                ("correo_facturacion", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Datos fiscales",
                "verbose_name_plural": "Datos fiscales",
                "db_table": "datos_fiscales",
                "indexes": [
                    models.Index(
                        fields=["tipo_entidad", "entidad_id"],
                        name="datos_fisca_tipo_en_53659d_idx",
                    )
                ],
            },
        ),
    ]
