# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autenticacion", "0001_initial"),
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("especialidad", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ciudad", models.CharField(blank=True, max_length=120)),
                ("estado_geografico", models.CharField(blank=True, max_length=120)),
                (
                    "calificacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("anios_experiencia", models.PositiveSmallIntegerField(default=0)),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Especialista",
                "verbose_name_plural": "Especialistas",
                "db_table": "especialistas",
                "ordering": ["-calificacion"],
            },
        ),
        migrations.CreateModel(
            name="ReporteMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("tipo_especialista", models.CharField(blank=True, max_length=100)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("resuelto", "Resuelto"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="abierto",
                        max_length=15,
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "especialista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes",
                        to="mantenimiento.especialista",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="propiedades.propiedad",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_mantenimiento",
                        to="autenticacion.propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de mantenimiento",
                "verbose_name_plural": "Reportes de mantenimiento",
                "db_table": "reportes_mantenimiento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResenaEspecialista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(help_text="Calificación de 1 a 5"),
                ),
                ("comentario", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "especialista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to="mantenimiento.especialista",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas_escritas",
                        to="autenticacion.propietario",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to="mantenimiento.reportemantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reseña de especialista",
                "verbose_name_plural": "Reseñas de especialistas",
                "db_table": "resenas_especialistas",
                "ordering": ["-created_at"],
                "unique_together": {("propietario", "reporte")},
            },
        ),
    ]
