# Generated by Django 4.2.7 on 2026-02-24 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mantenimiento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resenaespecialista",
            name="calificacion",
            field=models.PositiveSmallIntegerField(
                help_text="Calificación de 1 a 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
