# Generated by Django 6.0.2 on 2026-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arrendatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("folio_ine", models.CharField(blank=True, max_length=20)),
                ("mascotas", models.BooleanField(default=False)),
                ("hijos", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Arrendatario",
                "verbose_name_plural": "Arrendatarios",
                "db_table": "arrendatarios",
                "ordering": ["apellidos", "nombre"],
            },
        ),
    ]
