# Generated by Django 6.0.2 on 2026-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arrendatarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrendatario",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="arrendatarios/fotos/"
            ),
        ),
    ]
