# Generated by Django 4.2.7 on 2026-02-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0002_propietario_foto"),
        ("arrendatarios", "0002_arrendatario_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrendatario",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario que registró a este arrendatario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrendatarios",
                to="autenticacion.propietario",
            ),
        ),
    ]
