# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autenticacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobiliario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Mobiliario",
                "verbose_name_plural": "Mobiliario",
                "db_table": "mobiliario",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.TextField()),
                ("ciudad", models.CharField(max_length=120)),
                ("estado_geografico", models.CharField(max_length=120)),
                ("codigo_postal", models.CharField(blank=True, max_length=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("local", "Local comercial"),
                            ("oficina", "Oficina"),
                            ("terreno", "Terreno"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("costo_renta", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "superficie_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("rentada", "Rentada"),
                            ("mantenimiento", "En mantenimiento"),
                            ("inactiva", "Inactiva"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propiedades",
                        to="autenticacion.propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propiedad",
                "verbose_name_plural": "Propiedades",
                "db_table": "propiedades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropiedadDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100)),
                ("valor", models.CharField(max_length=255)),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="propiedades.propiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de propiedad",
                "verbose_name_plural": "Detalles de propiedad",
                "db_table": "propiedad_detalles",
                "unique_together": {("propiedad", "clave")},
            },
        ),
        migrations.CreateModel(
            name="PropiedadMobiliario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("malo", "Malo"),
                            ("reparacion", "En reparación"),
                        ],
                        default="bueno",
                        max_length=20,
                    ),
                ),
                (
                    "mobiliario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propiedades",
                        to="propiedades.mobiliario",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobiliarios",
                        to="propiedades.propiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobiliario de propiedad",
                "verbose_name_plural": "Mobiliario de propiedades",
                "db_table": "propiedad_mobiliario",
                "unique_together": {("propiedad", "mobiliario")},
            },
        ),
    ]
