# Generated by Django 6.0.2 on 2026-02-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiliario",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="mobiliario/fotos/"
            ),
        ),
        migrations.CreateModel(
            name="FotoPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="propiedades/fotos/")),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Marca esta foto como imagen principal de la propiedad",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="propiedades.propiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de propiedad",
                "verbose_name_plural": "Fotos de propiedad",
                "db_table": "propiedad_fotos",
                "ordering": ["orden", "-es_principal"],
            },
        ),
    ]
