# Generated by Django 6.0.2 on 2026-02-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arrendatarios", "0001_initial"),
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "renta_acordada",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "deposito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "dia_pago",
                    models.PositiveSmallIntegerField(
                        help_text="Día del periodo en que se cobra (1-31 para mensual)"
                    ),
                ),
                (
                    "periodo_pago",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("mensual", "Mensual"),
                            ("anual", "Anual"),
                        ],
                        default="mensual",
                        max_length=10,
                    ),
                ),
                (
                    "incremento_anual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de incremento anual",
                        max_digits=5,
                    ),
                ),
                (
                    "penalizacion_anticipada",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Penalización por terminación anticipada",
                        max_digits=12,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("renovado", "Renovado"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arrendatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="arrendatarios.arrendatario",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="propiedades.propiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "db_table": "contratos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistorialContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(max_length=15)),
                ("estado_nuevo", models.CharField(max_length=15)),
                ("motivo", models.TextField(blank=True)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de contrato",
                "verbose_name_plural": "Historial de contratos",
                "db_table": "historial_contratos",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
